name: zksync-os-v31-triple

services:
  l1:
    image: ghcr.io/foundry-rs/foundry:v1.5.1
    platform: linux/amd64
    user: root
    entrypoint: ""
    ports:
      - 5110:5010
    volumes:
      - ./chain-configs/dev/zksyncos/l1-state-3chains.json.gz:/zkos-l1-state.json.gz:ro
      - l1state:/home/foundry/l1state
    command: |
      bash -c "
      gzip -dc /zkos-l1-state.json.gz > /home/foundry/l1state/state-v31.json;
      anvil --state=/home/foundry/l1state/state-v31.json --port 5010 --host 0.0.0.0
      "
    healthcheck:
      test: ["CMD-SHELL", "cast chain-id -r http://localhost:5010"]
      interval: 10s
      timeout: 5s
      retries: 10

  zksyncos-l2a:
    image: ghcr.io/matter-labs/zksync-os-server:v0.15.1
    platform: linux/amd64
    user: root
    working_dir: /app
    entrypoint: ""
    command: ["/usr/bin/tini", "--", "zksync-os-server", "--config", "/app/local-chains/v31.0/multi_chain/chain_6565.yaml"]
    environment:
      GENERAL_L1_RPC_URL: http://l1:5010
    ports:
      - 5150:3050
    volumes:
      - ../zksync-os-server/local-chains:/app/local-chains:ro
    depends_on:
      l1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/3050"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

  zksyncos-l2b:
    image: ghcr.io/matter-labs/zksync-os-server:v0.15.1
    platform: linux/amd64
    user: root
    working_dir: /app
    entrypoint: ""
    command: ["/usr/bin/tini", "--", "zksync-os-server", "--config", "/app/local-chains/v31.0/multi_chain/chain_6566.yaml"]
    environment:
      GENERAL_L1_RPC_URL: http://l1:5010
    ports:
      - 5151:3051
    volumes:
      - ../zksync-os-server/local-chains:/app/local-chains:ro
    depends_on:
      l1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/3051"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

  zksyncos-l2c:
    image: ghcr.io/matter-labs/zksync-os-server:v0.15.1
    platform: linux/amd64
    user: root
    working_dir: /app
    entrypoint: ""
    command: ["/usr/bin/tini", "--", "zksync-os-server", "--config", "/app/local-chains/v31.0/multi_chain/chain_6567.yaml"]
    environment:
      GENERAL_L1_RPC_URL: http://l1:5010
    ports:
      - 5152:3052
    volumes:
      - ../zksync-os-server/local-chains:/app/local-chains:ro
    depends_on:
      l1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/3052"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

volumes:
  l1state:
